name: Labeler

on:
  - pull_request_target
  - workflow_dispatch

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  label:
    permissions:
      contents: read  # for actions/labeler to determine modified files
      pull-requests: write  # for actions/labeler to add labels to PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          dot: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
